### PR TITLE
Fix parameters order in POST requests

### PR DESCRIPTION
**Pull request by jschaeff**
This fix has been tested in Resif environment.

Please someone check if it works against the #29 issue.

### CODE REVIEW

**Comment by jschaeff** [comment]
This fix has been deployed at RESIF and is working fine.

a10y is now able to list restricted network's availability.

@jbienkowski could you test on your side and apply the PR ?

**Review by sheimers — COMMENTED** [review]
It fails here, from the log: 

```
post_params = [(k for k in Parameters().todict() if k not in exclude]
                                                                        ^
SyntaxError: closing parenthesis ']' does not match opening parenthesis '('

```
Obviously there is an orphaned '(' left. Should it be removed, or re-added after 'exclude'?

**Comment by jschaeff** [comment]
I fixed it and merge in master.
I can not test locally because we run another availability code.

**Comment by sheimers** [comment]
Thanks for the fast fix.

**Pull request merged**
